In [1]:
import os
import pandas as pd

In [2]:
cwd = os.path.abspath('') 
cwd

'C:\\Users\\madad\\Desktop\\2020.10.11_192407.tar'

In [3]:
files = os.listdir(cwd) 
files

['.ipynb_checkpoints',
 'Aggregated_Results_Batterystats.csv',
 'Aggregated_Results_Full.csv',
 'config.json',
 'data',
 'experiment.log',
 'progress.xml',
 'Untitled.ipynb']

In [4]:
# Read data from file 'Aggregated_Results_Batterystats.csv' 
aggregated_battery_stats = pd.read_csv('Aggregated_Results_Batterystats.csv') 
# Preview the first 5 lines of the loaded data 
aggregated_battery_stats.head()

,device,subject,browser,batterystats_Joule_calculated
0,nexus5x,http-192-168-100-103-9191-local_websites-www-i...,chrome,49.743360
1,nexus5x,http-192-168-100-103-9191-local_websites-www-w...,chrome,64.089072
2,nexus5x,http-192-168-100-103-9191-local_websites-www-w...,chrome,61.712856
3,nexus5x,http-192-168-100-103-9191-local_websites-www-o...,chrome,49.466808
4,nexus5x,http-192-168-100-103-9191-local_websites-www-b...,chrome,43.525440

In [5]:
navigation_timing_df = pd.DataFrame(columns=['headerSize', 'workerTime', 'fetchTime', 
                                            'timeToFirstByte', 'downloadTime', 'totalTime',
                                            'totalLoadTime', 'dnsLookupTime']) # relevant
fcp_df = pd.DataFrame(columns=['fcp']) # relevant
fp_df = pd.DataFrame(columns=['fp']) # relevant
# fid_df = pd.DataFrame(columns=['fid'])
# cls_df = pd.DataFrame(columns=['cls'])
# lcp_df = pd.DataFrame(columns=['lcp'])
# fid_df = pd.DataFrame(columns=['fid'])
# network_information_df = pd.DataFrame(columns=['rtt', 'saveData', 'effectiveType', 'downlink'])
# storage_estimate_df = pd.DataFrame(columns=['usage', 'indexedDB', 'quota', 'caches'])
# tbt_df = pd.DataFrame(columns=['tbt'])

In [6]:
for i in range (0, len(aggregated_battery_stats)):
    website = aggregated_battery_stats['subject'].get(i)
    perfumejs_path = f"{cwd}\\data\\nexus5x\\{website}\\chrome\\perfume_js\\"
    
    for file in os.listdir(perfumejs_path):
        if os.path.isfile(os.path.join(perfumejs_path, file)):
            if 'navigationTiming_results_' in file:
                navigation_timing_stats_for_website = pd.read_csv(f"{perfumejs_path}{file}")
                navigation_timing_df = navigation_timing_df.append(navigation_timing_stats_for_website[:1], sort=False, ignore_index=True)
            
            if 'fcp_results_' in file:
                fcp_for_website = pd.read_csv(f"{perfumejs_path}{file}")
                fcp_df = fcp_df.append(fcp_for_website[:1], sort=False, ignore_index=True)
        
            if 'fp_results_' in file:
                fp_for_website = pd.read_csv(f"{perfumejs_path}{file}")
                fp_df = fp_df.append(fp_for_website[:1], sort=False, ignore_index=True)

In [7]:
assert(i+1==len(navigation_timing_df))
assert(i+1==len(fcp_df))
assert(i+1==len(fp_df))
assert(i+1==len(aggregated_battery_stats))

In [8]:
navigation_timing_df.head()

,headerSize,workerTime,fetchTime,timeToFirstByte,downloadTime,totalTime,totalLoadTime,dnsLookupTime
0,341,0,153.4,3.9,135.2,139.1,5018,0
1,341,0,76.5,4.5,42.5,47.0,1842,0
2,334,0,88.7,13.7,49.0,62.7,1008,0
3,342,0,40.5,4.2,3.9,8.1,2730,0
4,346,0,143.6,34.8,80.5,115.3,1015,0

In [9]:
fcp_df.head()

      fcp
0  1472.3
1  1282.0
2  1172.7
3  1787.4
4  1185.4

In [10]:
fp_df.head()

       fp
0  1472.3
1  1282.0
2  1172.7
3  1787.4
4  1185.4

In [11]:
aggregated_results = pd.concat([aggregated_battery_stats, navigation_timing_df, fcp_df, fp_df], join = 'outer', axis = 1) 
assert(30==len(aggregated_results))

In [12]:
aggregated_results.head()

,device,subject,browser,batterystats_Joule_calculated,headerSize,workerTime,fetchTime,timeToFirstByte,downloadTime,totalTime,totalLoadTime,dnsLookupTime,fcp,fp
0,nexus5x,http-192-168-100-103-9191-local_websites-www-i...,chrome,49.743360,341,0,153.4,3.9,135.2,139.1,5018,0,1472.3,1472.3
1,nexus5x,http-192-168-100-103-9191-local_websites-www-w...,chrome,64.089072,341,0,76.5,4.5,42.5,47.0,1842,0,1282.0,1282.0
2,nexus5x,http-192-168-100-103-9191-local_websites-www-w...,chrome,61.712856,334,0,88.7,13.7,49.0,62.7,1008,0,1172.7,1172.7
3,nexus5x,http-192-168-100-103-9191-local_websites-www-o...,chrome,49.466808,342,0,40.5,4.2,3.9,8.1,2730,0,1787.4,1787.4
4,nexus5x,http-192-168-100-103-9191-local_websites-www-b...,chrome,43.525440,346,0,143.6,34.8,80.5,115.3,1015,0,1185.4,1185.4

In [13]:
aggregated_results.to_csv('Aggregated_Results_Full.csv')